plugins:

  starlingx:
    executor: central_deployment_agent
    source: https://github.com/cloudify-cosmo/cloudify-starlingx-plugin/archive/0.0.1.zip
    package_name: cloudify-starlingx-plugin
    package_version: '0.0.1'

dsl_definitions:

  client_config: &client_config
    client_config:
      type: cloudify.types.starlingx.ClientConfig
      description: Your OpenStack client configuration.
      required: false

  # Every resource uses this property unless noted.
  external_resource: &external_resource
    use_external_resource:
      description: Indicate whether the resource exists or if Cloudify should create the resource, true if you are bringing an existing resource, false if you want cloudify to create it.
      type: boolean
      default: true

data_types:

  cloudify.types.starlingx.ClientConfig:
    # See: https://docs.openstack.org/python-openstackclient/pike/cli/man/openstack.html.
    properties:
      auth_url:
        type: string
        description: Your OpenStack Client Authorization URL.
        required: false
      username:
        type: string
        description: Your OpenStack username.
        required: false
      password:
        type: string
        description: Your OpenStack password.
        required: false
      project_name:
        type: string
        description: The name of your OpenStack project.
        required: false
      tenant_name:
        type: string
        description: The name of your OpenStack tenant.
        required: false
      region_name:
        type: string
        description: The region where you want this particular resource to be created.
        required: false
      user_domain_id:
        type: string
        description: The user domain id
        required: false
      project_domain_id:
        type: string
        description: The Project domain id
        required: false
      user_domain_name:
        description: Domain name to operate on.
        type: string
        required: false
      project_domain_name:
        description: Project domain name to operate on.
        type: string
        required: false
      logging:
        description: Logging configuration.
        type: cloudify.types.openstack.Logging
        required: false
      insecure:
        description: If true, SSL validation is skipped.
        type: boolean
        required: false
        default: false
      cacert:
        description: Path to CA certificate to validate OpenStack's endpoint with.
        type: string
        required: false
      kwargs:
        description: >
          A dictionary of keys and values that is not validated
          but will override other values in the client config.
        default: {}

  cloudify.types.starlingx.Controller:
    properties: {}

  cloudify.types.starlingx.Subcloud:
    properties: {}

node_types:

  cloudify.nodes.starlingx.Controller:
    derived_from: cloudify.nodes.Root
    properties:
      <<: *external_resource
      <<: *client_config
      resource_config:
        type: cloudify.types.starlingx.Controller
    interfaces:
      cloudify.interfaces.lifecycle:
        poststart:
          implementation: starlingx.starlingx_plugin.resources.controller.poststart


  cloudify.nodes.starlingx.Subcloud:
    derived_from: cloudify.nodes.Root
    properties:
      <<: *external_resource
      <<: *client_config
      resource_config:
        type: cloudify.types.starlingx.Subcloud
    interfaces:
      cloudify.interfaces.lifecycle:
        poststart:
          implementation: starlingx.starlingx_plugin.resources.subcloud.poststart

relationships:

  cloudify.relationships.starlingx.subcloud_connected_to_controller:
    derived_from: cloudify.relationships.connected_to
    source_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        preconfigure:
          implementation: starlingx.starlingx_plugin.resources.subcloud.preconfigure
