version: 2.1

checkout:
  post:
    - >
      if [ -n "$CI_PULL_REQUEST" ]; then
        PR_ID=${CI_PULL_REQUEST##*/}
        git fetch origin +refs/pull/$PR_ID/merge:
        git checkout -qf FETCH_HEAD
      fi


executors:

  py36:
    docker:
      - image: circleci/python:3.6

  wagon_generator:
    machine:
      image: ubuntu-1604:201903-01

  cloudify-machine:
    machine:
      image: ubuntu-1604:201903-01

  cloudify-machine-510:
    machine:
      image: ubuntu-1604:201903-01

commands:

  run_unittest:
    steps:
      - checkout
      - run:
          name: install tox
          command: pip install --user tox
      - run:
          name: Run Flake8
          command: /home/circleci/.local/bin/tox -e flake8
      - run:
         name: Run nosetest
         command: python -m pytest


  generate_py36_wagon:
    steps:
      - run:
          name: Create Workspace Build directory.
          command: mkdir -p workspace/build
      - run:
          name: Build py27py36 Wagon
          command: |
              git clone https://github.com/cloudify-cosmo/cloudify-wagon-build-containers.git
              docker build -t cloudify-centos-7-wagon-builder-py3 cloudify-wagon-build-containers/centos_7_py3
              docker run -v ~/project/:/packaging cloudify-centos-7-wagon-builder-py3
      - run:
          name: copy wagon to workspace
          command: cp *.wgn workspace/build/
      - persist_to_workspace:
          root: workspace
          paths:
            - build/*

  generate_rhel_py36_wagon:
    steps:
      - run:
          name: Create Workspace Build directory.
          command: mkdir -p workspace/build
      - run:
          name: Build RHEL py27py36 Wagon
          command: |
              git clone https://github.com/cloudify-cosmo/cloudify-wagon-build-containers.git
              docker build -t cloudify-redhat-7-wagon-builder-py3 cloudify-wagon-build-containers/redhat_7_py3 --build-arg USERNAME="$USERNAME" --build-arg PASSWORD="$PASSWORD"
              docker run -v ~/project/:/packaging cloudify-redhat-7-wagon-builder-py3
      - run:
          name: copy wagon to workspace
          command: cp *.wgn workspace/build/
      - persist_to_workspace:
          root: workspace
          paths:
            - build/*


  release_plugin:
    steps:
      - run:
          name: "Pull Submodules"
          command: |
            git submodule update --remote --recursive
      - run:
          name: Download pip
          command: curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
      - run:
          name: Install pip
          command: sudo python get-pip.py
      - run:
          name: Install virtualenv
          command: pip install --user virtualenv
      - run:
          name: Init virtualenv
          command: virtualenv env
      - run:
          name: install tox
          command: pip install --user pygithub pyyaml==5.3.1
      - run:
          name: upgrade setuptools
          command: pip install --upgrade setuptools
      - run:
          name: install local project
          command: pip install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/latest.zip
      - attach_workspace:
          at: workspace
      - run: python .circleci/package_release.py

  validate_version:
    steps:
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote --recursive
      - run:
          name: Download pip
          command: curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
      - run:
          name: Install pip
          command: sudo python get-pip.py
      - run:
          name: Install virtualenv
          command: pip install --user virtualenv
      - run:
          name: Init virtualenv
          command: virtualenv env
      - run:
          name: install tox
          command: pip install --user pygithub pyyaml==3.10
      - run:
          name: upgrade setuptools
          command: pip install --upgrade setuptools
      - run:
          name: install local project
          command: pip install https://github.com/cloudify-incubator/cloudify-ecosystem-test/archive/latest.zip
      - attach_workspace:
          at: workspace
      - run: python .circleci/validate_version.py


jobs:

  unittests_py36:
    executor: py36
    steps:
      - run_unittest

  validate_version:
    executor: py36
    steps:
      - checkout
      - validate_version

  wagon:
    executor: wagon_generator
    steps:
      - checkout
      - generate_py36_wagon

  rhel_wagon:
    executor: wagon_generator
    steps:
      - checkout
      - generate_rhel_py36_wagon

  release:
    executor: py36
    steps:
      - checkout
      - release_plugin

workflows:
  version: 2
  tests:
    jobs:
      - unittests_py36
      - validate_version
      - wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - rhel_wagon:
          filters:
            branches:
              only: /([0-9\.]*\-build|master|dev)/
      - release:
          filters:
            branches:
              only: /master/

          requires:
            - wagon
            - rhel_wagon

  nightly:
    triggers:
    - schedule:
        cron: "0 3 * * *"
        filters:
          branches:
            only:
              - master
    jobs:
      - unittests_py36
